/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const FileType = IDL.Variant({ 'video' : IDL.Null, 'photo' : IDL.Null });
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const HistoryRecord = IDL.Record({
  'id' : IDL.Text,
  'noiseReduction' : IDL.Bool,
  'originalBlob' : ExternalBlob,
  'sharpness' : IDL.Nat,
  'fileSize' : IDL.Nat,
  'fileType' : FileType,
  'filename' : IDL.Text,
  'timestamp' : IDL.Nat,
  'processedBlob' : ExternalBlob,
  'scaleFactor' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addHistoryRecord' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        FileType,
        IDL.Nat,
        IDL.Nat,
        IDL.Bool,
        ExternalBlob,
        ExternalBlob,
        IDL.Nat,
      ],
      [],
      [],
    ),
  'clearAllHistoryRecords' : IDL.Func([], [], []),
  'deleteHistoryRecord' : IDL.Func([IDL.Text], [], []),
  'getAllHistoryRecords' : IDL.Func([], [IDL.Vec(HistoryRecord)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const FileType = IDL.Variant({ 'video' : IDL.Null, 'photo' : IDL.Null });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const HistoryRecord = IDL.Record({
    'id' : IDL.Text,
    'noiseReduction' : IDL.Bool,
    'originalBlob' : ExternalBlob,
    'sharpness' : IDL.Nat,
    'fileSize' : IDL.Nat,
    'fileType' : FileType,
    'filename' : IDL.Text,
    'timestamp' : IDL.Nat,
    'processedBlob' : ExternalBlob,
    'scaleFactor' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addHistoryRecord' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          FileType,
          IDL.Nat,
          IDL.Nat,
          IDL.Bool,
          ExternalBlob,
          ExternalBlob,
          IDL.Nat,
        ],
        [],
        [],
      ),
    'clearAllHistoryRecords' : IDL.Func([], [], []),
    'deleteHistoryRecord' : IDL.Func([IDL.Text], [], []),
    'getAllHistoryRecords' : IDL.Func([], [IDL.Vec(HistoryRecord)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };